### ISSUE TITLE
Finish the exercise!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/e-s3-evaluacion-intermedia-babelarr#1]
Well done @babelarr!

Some tips to improve it:

- [x] Move `li` outside 'Pokemon' component, this way it is a simple card that we can use anywhere not only inside a `ul`
- [x] Add title of the page (Mi lista de Pokemons)
- [x] Use `id` of pokemon for the `key` of React when mapping
- [x] Use propTypes to check your props
- [x] Review metadata on index.html (lang, title...)
- [x] Publish on Github Pages
- [x] Remove unused files and their references

Go for it!

**Comment by babelarr** [comment]
Hi @oneeyedman !! Thanks for your tips :)

I think everything is done, please tell me if you want to change something else.

Good weekend!
